### ISSUE TITLE
Salt calculation

### ISSUE THREAD

**Issue by rrTTbb** [Technica-Engineering/MKAdaemon#1]
According to IEEE Std 802.1AE-2018 Salt is calculated:
The 64 least significant bits of the Salt are the 64 least significant bits of the MKA Key Server’s
Member Identifier (MI), the 16 next most significant bits of the Salt comprise the exclusive-or of the 16 next
most significant bits of that MI with the 16 most significant bits of the 32-bit MKA Key Number (KN), and
the 16 most significant bits of the Salt comprise the exclusive-or of the 16 most significant bits of that MI
with the 16 least significant bits of the KN

yet here it is calculated as:
`

    for (uint8_t i = 0U; i < 8U; i++) {
        ctx->SALT.key[i] = ctx->key_identifier.mi[i];
    }

    ctx->SALT.key[8] = ctx->key_identifier.mi[8] ^ (uint8_t)((ctx->key_identifier.kn & 0xFF000000U) >> 24U);
    ctx->SALT.key[9] = ctx->key_identifier.mi[9] ^ (uint8_t)((ctx->key_identifier.kn & 0x00FF0000U) >> 16U);
    ctx->SALT.key[10]= ctx->key_identifier.mi[10]^ (uint8_t)((ctx->key_identifier.kn & 0x0000FF00U) >> 8U);
    ctx->SALT.key[11]= ctx->key_identifier.mi[11]^ (uint8_t) (ctx->key_identifier.kn & 0x000000FFU);
`
Which means that MSBits are just a copy of MSBits of MI and XOR is done on LSBits of MI,
My assumption is that SALT and mi buffers are network byte order.

**Comment by andreu-montiel-te** [comment]
Hi @rrTTbb 
You're assuming right, this is in network byte order / big endian. I think you're right, the XOR should be applied to the most significant bits which are the first indexes of the array, not the last ones. We'll have a look at this part.
Thanks for letting us know!

**Comment by andreu-montiel-te** [comment]
Hello @rrTTbb ,
@fpedrera-technica just uploaded PR #3 with what we think the fix should be. The XOR is now applied to the MSB of MI. However the spec is quite confusing regarding the combination of KN with MI for the remaining 32 bits;  it describes the operation in groups of 16 bits, and it appears the 16 msb of KN are to be combined with the 16 lsb of the remaining 32 bits (referenced as "16 next msb of MI").
Would you mind having a look at the fix to confirm everything is ok? Do you have any means to try this fix with a different implementation?
Thank you!
Andreu
