### ISSUE TITLE
Checking for GoogleTest submodule : no, please download submodules to run UTs error received

### ISSUE THREAD

**Issue by ashravti** [Technica-Engineering/MKAdaemon#5]
![image](https://user-images.githubusercontent.com/125255787/218411324-18f69b1d-d162-45bb-827e-ad7340b8186f.png)
Hi,

I am trying to compile and run the mka daemon. I am getting the following error when i run this command : python waf test
Checking for GoogleTest submodule : no, please download submodules to run UTs error received. How can i get this resolved ?

Thanks,
Ashwin

**Comment by andreu-montiel-te** [comment]
Hi @ashravti ,

You can run this command to download the git submodules:
 $ git submodule update --init --recursive

Then run the configure step again.

Let me know if it worked.

Andreu

**Comment by ashravti** [comment]
hi Andreu,

thanks a lot for the quick response, that helped and i was able to execute all the step up till ### python waf test --targets=kay --gtest_filter=TxWhenClient.InstallSak. 

i believe your project could actually help me verify a system use case that i am currently trying to support. we have an ethernet phy which is capable of doing hardware macsec (encrypt/decrypt) similar to how linux kernel does software macsec, we plan to do a hardware offloading to the ethernet phy. but before that, as a first step i was trying to connect two linux PCs running ubuntu using a rj45 ethernet cable, enable software macsec on both the PCs as mentioned in this article : https://costiser.ro/2016/08/01/macsec-implementation-on-linux/#.Y-n9ERxBw5k and then use the daemon that you have developed to do the macsec key agreement (MKA). can this be done ? If yes, how do i go ahead with this, and are there any documents that i could follow to get this usecase up and working ?

thanks,
Ashwin

**Comment by andreu-montiel-te** [comment]
Hi @ashravti ,

Yes, your use case should be very straightforward. You just need to have the daemon compiled in both PC's,
and create the appropriate config files. Most of the default settings in the example file should work, maybe you just want to limit the daemon to one channel, and "device" should reference your physical interface.

Maybe as a first step for the HW offloading I'd advise to aim for the default ciphersuite GCM_AES_128 non XPN, then once it's working go for the rest of ciphersuites (GCM_AES_128_XPN, GCM_AES_256, GCM_AES_256_XPN).

BR,
Andreu

**Comment by ashravti** [comment]
hi Andreu,

Is there any documentation provided for how i can do that ? we are quite new to software macsec (macsec on linux) as we are hardware designers. i did go through some of the tests you have created, any specific example test which i can use for this or maybe tweak to get this system use case working ?

Thanks,
Ashwin

**Comment by andreu-montiel-te** [comment]
I'll close the ticket, please open a new one if you find a bug. Thanks!
